[package]
name = "petram-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
lazy_static = "1.5.0"
strum = "0.26.3"
strum_macros = "0.26.4"

[[bin]]
name = "petram"
path = "src/main.rs"

[lib]
name = "petram"
path = "lib/lib.rs"
