[package]
name = "petram-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }

[[bin]]
name = "petram"
path = "src/main.rs"

[lib]
name = "petram"
path = "lib/lib.rs"
